In [1]:
from minimal_rules import extract_minimal_rules
import numpy as np

In [2]:
rule_set = extract_minimal_rules("data.csv", decision_column="diagnosis_class")

In [3]:
for idx, rule in enumerate(rule_set.rules, 1):
    print(f"{idx}. {rule}")

1. IF drowsiness = False ∧ attention_impairment = True THEN diagnosis_class = '0'
2. IF incoordination = True ∧ attention_impairment = True THEN diagnosis_class = '0'
3. IF nystagmus = True ∧ attention_impairment = True THEN diagnosis_class = '0'
4. IF stupor = True ∧ attention_impairment = True THEN diagnosis_class = '0'
5. IF unsteady_gait = True ∧ attention_impairment = True THEN diagnosis_class = '0'
6. IF blurred_vision = False ∧ incoordination = True THEN diagnosis_class = '0'
7. IF blurred_vision = False ∧ stupor = True THEN diagnosis_class = '0'
8. IF blurred_vision = False ∧ unsteady_gait = True THEN diagnosis_class = '0'
9. IF stupor = True ∧ depressed_reflexes = False THEN diagnosis_class = '0'
10. IF unsteady_gait = True ∧ depressed_reflexes = False THEN diagnosis_class = '0'
11. IF diplopia = False ∧ stupor = True THEN diagnosis_class = '0'
12. IF diplopia = False ∧ unsteady_gait = True THEN diagnosis_class = '0'
13. IF stupor = True ∧ dizziness = False THEN diagnosis_clas

In [ ]:
new_diagnosis_col = [np.random.choice(range(0,13), size=np.random.choice(range(1,5), p=[4/9, 3/9, 2/9, 0/9]), replace=False) for _ in range(14)]
new_diagnosis_col

[array([ 3, 10,  8]),
 array([12,  7,  8]),
 array([ 9,  8, 11]),
 array([ 3, 10]),
 array([9, 0, 1]),
 array([9]),
 array([3, 8]),
 array([12]),
 array([7]),
 array([2]),
 array([1]),
 array([7]),
 array([1, 3]),
 array([8])]