In [1]:
from minimal_rules import extract_minimal_rules
import numpy as np

In [2]:
rule_set = extract_minimal_rules("patients.csv", decision_column="diagnosis_class")

In [3]:
print(rule_set)
for idx, rule in enumerate(rule_set.rules, 1):
    print(f"{idx}. {rule}")

MinimalRuleSet(rules=[MinimalRule(antecedent={'nystagmus': '1'}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'dysphoric_mood': True}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'incoordination': True}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'palpitations': True}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'sporty': True}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'stupor': True}, decision=0), MinimalRule(antecedent={'attention_impairment': True, 'unsteady_gait': True}, decision=0), MinimalRule(antecedent={'palpitations': True, 'blurred_vision': False}, decision=0), MinimalRule(antecedent={'unsteady_gait': True, 'blurred_vision': False}, decision=0), MinimalRule(antecedent={'incoordination': True, 'dysphoric_mood': True}, decision=0), MinimalRule(antecedent={'palpitations': True, 'dysphoric_mood': True}, decision=0), MinimalRule(antecedent={'slurred_speech': True, 

In [4]:
new_diagnosis_col = [np.random.choice(range(0,13), size=np.random.choice(range(1,5), p=[4/9, 3/9, 2/9, 0/9]), replace=False) for _ in range(14)]
new_diagnosis_col

[array([9, 5, 1]),
 array([ 6, 12]),
 array([11]),
 array([2]),
 array([11]),
 array([5]),
 array([2]),
 array([12, 11]),
 array([ 2, 12,  8]),
 array([3]),
 array([2, 8]),
 array([9]),
 array([12,  1,  0]),
 array([ 5,  6, 12])]

In [7]:
with open("minimal_rules.pl", "w+") as f:
    for rule in rule_set.rules:
        f.write(str(rule) + "\n\n")