In [1]:
from minimal_rules import extract_minimal_rules
import numpy as np

d:\Studia\Magisterskie\M2\Systemy Ekspertowe\projekt\Medical-Expert-Systems\prolog\minimal_rules.py:20: SyntaxWarning: invalid escape sequence '\+'
  conditions.append(f"\+ symptom(Patient, {attr})")


In [2]:
rule_set = extract_minimal_rules("patients.csv", decision_column="diagnosis_class")

In [3]:
for idx, rule in enumerate(rule_set.rules, 1):
    print(f"{idx}. {rule}")

1. diagnosis(0, Patient) :-
  symptom(Patient, nystagmus).
2. diagnosis(0, Patient) :-
  symptom_class(Patient, tachycardia, True).
3. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, dysphoric_mood).
4. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, incoordination).
5. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, palpitations).
6. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, sporty).
7. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, stupor).
8. diagnosis(0, Patient) :-
  symptom(Patient, attention_impairment),
  symptom(Patient, unsteady_gait).
9. diagnosis(0, Patient) :-
  \+ symptom(Patient, blurred_vision),
  symptom(Patient, palpitations).
10. diagnosis(0, Patient) :-
  \+ symptom(Patient, blurred_vision),
  symptom(Patient, unsteady_gait).
11. diagnosis(0, Patient) :-
  symptom(Patient,

In [4]:
new_diagnosis_col = [np.random.choice(range(0,13), size=np.random.choice(range(1,5), p=[4/9, 3/9, 2/9, 0/9]), replace=False) for _ in range(14)]
new_diagnosis_col

[array([8, 5]),
 array([ 9, 10,  0]),
 array([8]),
 array([ 4,  7, 12]),
 array([7]),
 array([ 6, 11, 12]),
 array([ 1, 12]),
 array([7]),
 array([9]),
 array([9]),
 array([8]),
 array([12]),
 array([0, 9, 1]),
 array([0, 3, 8])]

In [ ]:
with open("minimal_rules.pl", "w+") as f:
    for rule in rule_set.rules:
        f.write(rule + "\n")